--- #YAML:1.0
name:                Jcode
version:             2.06
abstract:            Japanese Charset Handler
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    MIME::Base64:                  2.1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Dan Kogai <dankogai@dan.co.jp>
